openapi: 3.0.0
info:
  title: Express-typeorm-demo
  description: Demo API
  version: 1.0.0
paths:
# [GET] policyholders
  /api/policyholders:
    get:
      tags:
      - policyholders
      summary: Find policyholder and it's introducee
      parameters:
        - in: query
          name: code
          schema:
            type: string
            default: 19b00130-99e7-439d-96fd-3c4eee11660a
          description: "Policyholder's code, for this demo, try the root policy
           holders code in default, and use the response data
           for further testing"
      responses:  
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/policyholdersTree'
        400:
          description: Bad request
        404:
          description: User not found
        500:
          description: 'Server Error'
# [GET] policyholders' top
  /api/policyholders/{code}/top:
    get:
      tags:
      - policyholders
      summary: Find policyholder's top and it's introducee
      parameters:
        - in: path
          name: code
          schema:
            type: string
          description: "Policyholder's code, try [GET]policyholders
           and use the introducees in response data for this test"
      responses:  
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/policyholdersTree'
        400:
          description: Bad request
        404:
          description: User not found or does not have an introducer
        500:
          description: 'Server Error'

# definitions
components:
  schemas:
    policyholders:
      type: object
      required:
        - code
        - name
        - registration_date
      properties:
        code:
          type: string
          description: UUID, code for the policyholder
        name:
          type: string
          description: name of the policyholder
        introducer_code:
          type: string
          description: introducer's code
        registration_date:
          type: string
          description: ISO 8601, timestamp of registration
    policyholdersTree:
      type: object
      required:
        - code
        - name
        - registration_date
      properties:
        code:
          type: string
          description: UUID, code for the policyholder
        name:
          type: string
          description: name of the policyholder
        introducer_code:
          type: string
          description: introducer's code
        registration_date:
          type: string
          description: ISO 8601, timestamp of registration
        l:
          type: array
          description: left tree for introducees, ordered by registration date, level order traversal 
          items:
            $ref: '#/components/schemas/policyholders'
        r:
          type: array
          description: right tree for introducees, ordered by registration date, level order traversal
          items:
            $ref: '#/components/schemas/policyholders'
